### ISSUE TITLE
Can't interact with any Chromecast unless I restart the instance

### ISSUE THREAD

**Issue by Xyolyp** [angelnu/ioBroker.chromecast#55] opened 2019-03-16 21:43 UTC
I experience this issue every day.
I have set up a script to use the play/pause buttons and it works but after not using the Chromecast for a while the instance logs a lot of reconnecting to my devices and it can't interact with anything untill I restart the instance.

chromecast.0	2019-03-16 22:38:30.591	info	Reconnecting Fernseher Jonny & Laura to 192.168.178.72:8009
chromecast.0	2019-03-16 22:38:30.590	info	Received keep alive for disconnected device Fernseher Jonny & Laura
chromecast.0	2019-03-16 22:38:30.573	info	Reconnecting Fernseher Jonny & Laura to 192.168.178.72:8009
chromecast.0	2019-03-16 22:38:30.572	info	Received keep alive for disconnected device Fernseher Jonny & Laura
chromecast.0	2019-03-16 22:38:30.378	info	Reconnecting Alle Geräte to 192.168.178.86:34901
chromecast.0	2019-03-16 22:38:30.377	info	Received keep alive for disconnected device Alle Geräte
chromecast.0	2019-03-16 22:38:30.375	info	Reconnecting Schlafzimmer to 192.168.178.86:8009
chromecast.0	2019-03-16 22:38:30.375	info	Received keep alive for disconnected device Schlafzimmer
chromecast.0	2019-03-16 22:38:10.307	info	Reconnecting Alle Geräte to 192.168.178.86:34901
chromecast.0	2019-03-16 22:38:10.307	info	Received keep alive for disconnected device Alle Geräte
chromecast.0	2019-03-16 22:38:10.305	info	Reconnecting Schlafzimmer to 192.168.178.86:8009
chromecast.0	2019-03-16 22:38:10.304	info	Received keep alive for disconnected device Schlafzimmer
chromecast.0	2019-03-16 22:38:10.302	info	Reconnecting Fernseher Jonny & Laura to 192.168.178.72:8009
chromecast.0	2019-03-16 22:38:10.302	info	Received keep alive for disconnected device Fernseher Jonny & Laura
chromecast.0	2019-03-16 22:38:10.300	info	Reconnecting Fernseher Jonny & Laura to 192.168.178.72:8009
chromecast.0	2019-03-16 22:38:10.300	info	Received keep alive for disconnected device Fernseher Jonny & Laura
chromecast.0	2019-03-16 22:37:50.384	info	Reconnecting Alle Geräte to 192.168.178.86:34901
chromecast.0	2019-03-16 22:37:50.383	info	Received keep alive for disconnected device Alle Geräte
chromecast.0	2019-03-16 22:37:50.381	info	Reconnecting Schlafzimmer to 192.168.178.86:8009
chromecast.0	2019-03-16 22:37:50.381	info	Received keep alive for disconnected device Schlafzimmer
chromecast.0	2019-03-16 22:37:50.345	info	Reconnecting Fernseher Jonny & Laura to 192.168.178.72:8009
chromecast.0	2019-03-16 22:37:50.344	info	Received keep alive for disconnected device Fernseher Jonny & Laura
chromecast.0	2019-03-16 22:37:50.343	info	Reconnecting Fernseher Jonny & Laura to 192.168.178.72:8009
chromecast.0	2019-03-16 22:37:50.342	info	Received keep alive for disconnected device Fernseher Jonny & Laura
chromecast.0	2019-03-16 22:37:31.083	info	Reconnecting Fernseher Jonny & Laura to 192.168.178.72:8009
chromecast.0	2019-03-16 22:37:31.083	info	Received keep alive for disconnected device Fernseher Jonny & Laura
chromecast.0	2019-03-16 22:37:31.071	info	Reconnecting Fernseher Jonny & Laura to 192.168.178.72:8009
chromecast.0	2019-03-16 22:37:31.070	info	Received keep alive for disconnected device Fernseher Jonny & Laura
chromecast.0	2019-03-16 22:37:30.841	info	Reconnecting Alle Geräte to 192.168.178.86:34901
chromecast.0	2019-03-16 22:37:30.840	info	Received keep alive for disconnected device Alle Geräte
chromecast.0	2019-03-16 22:37:30.838	info	Reconnecting Schlafzimmer to 192.168.178.86:8009
chromecast.0	2019-03-16 22:37:30.837	info	Received keep alive for disconnected device Schlafzimmer
chromecast.0	2019-03-16 22:37:14.395	error	Fernseher_Jonny_&_Laura - Could not pause: undefined
chromecast.0	2019-03-16 22:37:10.553	info	Reconnecting Fernseher Jonny & Laura to 192.168.178.72:8009
chromecast.0	2019-03-16 22:37:10.553	info	Received keep alive for disconnected device Fernseher Jonny & Laura
chromecast.0	2019-03-16 22:37:10.551	info	Reconnecting Fernseher Jonny & Laura to 192.168.178.72:8009
chromecast.0	2019-03-16 22:37:10.550	info	Received keep alive for disconnected device Fernseher Jonny & Laura
chromecast.0	2019-03-16 22:37:10.406	info	Reconnecting Alle Geräte to 192.168.178.86:34901

**Comment by Xyolyp** [comment] 2019-03-20 20:45
![Screenshot_20190320-214127](https://user-images.githubusercontent.com/13995942/54717835-63337500-4b59-11e9-80b0-4fd24192c4de.png)
Attached is a screenshot of the debug log while the issue was present

**Comment by angelnu** [comment] 2019-03-31 22:19
Thanks for the log - I needed the debug level to see what the problem is and why the reconnects we not working.

I was not cleaning up completely when closing the old connection so the connect is being ignored. Fixed now in the _castv2-player_ 2.0.4 . If you update the chromecast adapter it should fetch the latest version of the library.

Please post another log if the reconnect fails.

**Closed** 2019-03-31 22:20 UTC
